Autres:
    type: entity
    table: autres
    indexes:
        fk_Autres_region1_idx:
            columns:
                - region_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        texte:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
    manyToOne:
        region:
            targetEntity: Region
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                region_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
