Bureaux:
    type: entity
    table: bureaux
    indexes:
        fk_bureaux_type_annonce1_idx:
            columns:
                - type_annonce_id
        fk_bureaux_region1_idx:
            columns:
                - region_id
    id:
        id:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        titre:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        confort:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
        superficie:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        numEtage:
            type: integer
            nullable: true
            unsigned: false
            comment: ''
            column: num_etage
        prix:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
        anneeConstruction:
            type: string
            nullable: true
            length: 45
            fixed: false
            comment: ''
            column: annee_construction
        texte:
            type: string
            nullable: true
            length: 1000
            fixed: false
            comment: ''
        typeAnnonce:
            targetEntity: TypeAnnonce
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                type_annonce_id:
                    referencedColumnName: id
            orphanRemoval: false
        region:
            targetEntity: Region
            cascade: {  }
            mappedBy: null
            inversedBy: null
            joinColumns:
                region_id:
                    referencedColumnName: id
            orphanRemoval: false
    lifecycleCallbacks: {  }
