annonce:
    path:     /
    defaults: { _controller: "ApplicationHomeBundle:Annonce:index" }

annonce_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationHomeBundle:Annonce:show" }

annonce_new:
    path:     /new
    defaults: { _controller: "ApplicationHomeBundle:Annonce:new" }

annonce_create:
    path:     /create
    defaults: { _controller: "ApplicationHomeBundle:Annonce:create" }
    requirements: { _method: post }

annonce_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationHomeBundle:Annonce:edit" }

annonce_update:
    path:     /{id}/update
    defaults: { _controller: "ApplicationHomeBundle:Annonce:update" }
    requirements: { _method: post|put }

annonce_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationHomeBundle:Annonce:delete" }
    requirements: { _method: post|delete }
