bureaux:
    path:     /
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:index" }

bureaux_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:show" }

bureaux_new:
    path:     /new
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:new" }

bureaux_create:
    path:     /create
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:create" }
    requirements: { _method: post }

bureaux_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:edit" }

bureaux_update:
    path:     /{id}/update
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:update" }
    requirements: { _method: post|put }

bureaux_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationHomeBundle:Bureaux:delete" }
    requirements: { _method: post|delete }
