region:
    path:     /
    defaults: { _controller: "ApplicationHomeBundle:Region:index" }

region_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationHomeBundle:Region:show" }

region_new:
    path:     /new
    defaults: { _controller: "ApplicationHomeBundle:Region:new" }

region_create:
    path:     /create
    defaults: { _controller: "ApplicationHomeBundle:Region:create" }
    requirements: { _method: post }

region_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationHomeBundle:Region:edit" }

region_update:
    path:     /{id}/update
    defaults: { _controller: "ApplicationHomeBundle:Region:update" }
    requirements: { _method: post|put }

region_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationHomeBundle:Region:delete" }
    requirements: { _method: post|delete }
