typeannonceclient:
    path:     /
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:index" }

typeannonceclient_show:
    path:     /{id}/show
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:show" }

typeannonceclient_new:
    path:     /new
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:new" }

typeannonceclient_create:
    path:     /create
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:create" }
    requirements: { _method: post }

typeannonceclient_edit:
    path:     /{id}/edit
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:edit" }

typeannonceclient_update:
    path:     /{id}/update
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:update" }
    requirements: { _method: post|put }

typeannonceclient_delete:
    path:     /{id}/delete
    defaults: { _controller: "ApplicationHomeBundle:TypeAnnonceClient:delete" }
    requirements: { _method: post|delete }
